# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-28 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellybean', '0006_auto_20180728_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='rest_name',
            field=models.CharField(max_length=100, verbose_name='Restaurant Name'),
        ),
    ]
