# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-29 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bellybean', '0009_auto_20180729_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='dish_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bellybean.Dish'),
        ),
        migrations.AlterField(
            model_name='order',
            name='item_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bellybean.Restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rest_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Restaurant Name'),
        ),
    ]
