# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-29 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellybean', '0012_auto_20180729_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
