# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-29 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bellybean', '0013_auto_20180729_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item_name',
        ),
    ]
