# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-30 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellybean', '0014_remove_order_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
