# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-30 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellybean', '0016_auto_20180730_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item_name',
            field=models.CharField(max_length=100, verbose_name='Your Address'),
        ),
    ]
