# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-01 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellybean', '0017_auto_20180730_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
