# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-01 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellybean', '0018_order_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
